// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: helloworld/patients.proto

package patients

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Patients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patient []*Patient `protobuf:"bytes,1,rep,name=patient,proto3" json:"patient,omitempty"`
}

func (x *Patients) Reset() {
	*x = Patients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_patients_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patients) ProtoMessage() {}

func (x *Patients) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_patients_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patients.ProtoReflect.Descriptor instead.
func (*Patients) Descriptor() ([]byte, []int) {
	return file_helloworld_patients_proto_rawDescGZIP(), []int{0}
}

func (x *Patients) GetPatient() []*Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type Patient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age             int32  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Sex             string `protobuf:"bytes,4,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Smoker          bool   `protobuf:"varint,5,opt,name=Smoker,proto3" json:"Smoker,omitempty"`
	CigsPerDay      int32  `protobuf:"varint,6,opt,name=CigsPerDay,proto3" json:"CigsPerDay,omitempty"`
	PrevalentStroke bool   `protobuf:"varint,7,opt,name=PrevalentStroke,proto3" json:"PrevalentStroke,omitempty"`
	Diabetes        bool   `protobuf:"varint,8,opt,name=Diabetes,proto3" json:"Diabetes,omitempty"`
}

func (x *Patient) Reset() {
	*x = Patient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_patients_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_patients_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_helloworld_patients_proto_rawDescGZIP(), []int{1}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Patient) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Patient) GetSmoker() bool {
	if x != nil {
		return x.Smoker
	}
	return false
}

func (x *Patient) GetCigsPerDay() int32 {
	if x != nil {
		return x.CigsPerDay
	}
	return 0
}

func (x *Patient) GetPrevalentStroke() bool {
	if x != nil {
		return x.PrevalentStroke
	}
	return false
}

func (x *Patient) GetDiabetes() bool {
	if x != nil {
		return x.Diabetes
	}
	return false
}

type GetPatientByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPatientByIdRequest) Reset() {
	*x = GetPatientByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworld_patients_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientByIdRequest) ProtoMessage() {}

func (x *GetPatientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_patients_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPatientByIdRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_patients_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatientByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_helloworld_patients_proto protoreflect.FileDescriptor

var file_helloworld_patients_proto_rawDesc = []byte{
	0x0a, 0x19, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x08, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x07, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x07,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x6d, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x53, 0x6d, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x69, 0x67, 0x73, 0x50,
	0x65, 0x72, 0x44, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x69, 0x67,
	0x73, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x76, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x50, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x61, 0x62, 0x65, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x44, 0x69, 0x61, 0x62, 0x65, 0x74, 0x65, 0x73, 0x22, 0x27, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x6d, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x08, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x25,
	0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x08, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x08, 0x2e, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_helloworld_patients_proto_rawDescOnce sync.Once
	file_helloworld_patients_proto_rawDescData = file_helloworld_patients_proto_rawDesc
)

func file_helloworld_patients_proto_rawDescGZIP() []byte {
	file_helloworld_patients_proto_rawDescOnce.Do(func() {
		file_helloworld_patients_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworld_patients_proto_rawDescData)
	})
	return file_helloworld_patients_proto_rawDescData
}

var file_helloworld_patients_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_helloworld_patients_proto_goTypes = []interface{}{
	(*Patients)(nil),              // 0: Patients
	(*Patient)(nil),               // 1: Patient
	(*GetPatientByIdRequest)(nil), // 2: GetPatientByIdRequest
}
var file_helloworld_patients_proto_depIdxs = []int32{
	1, // 0: Patients.patient:type_name -> Patient
	2, // 1: PatientService.GetPatientById:input_type -> GetPatientByIdRequest
	1, // 2: PatientService.InsertPatient:input_type -> Patient
	1, // 3: PatientService.GetPatientById:output_type -> Patient
	1, // 4: PatientService.InsertPatient:output_type -> Patient
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_helloworld_patients_proto_init() }
func file_helloworld_patients_proto_init() {
	if File_helloworld_patients_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworld_patients_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_patients_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworld_patients_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworld_patients_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_patients_proto_goTypes,
		DependencyIndexes: file_helloworld_patients_proto_depIdxs,
		MessageInfos:      file_helloworld_patients_proto_msgTypes,
	}.Build()
	File_helloworld_patients_proto = out.File
	file_helloworld_patients_proto_rawDesc = nil
	file_helloworld_patients_proto_goTypes = nil
	file_helloworld_patients_proto_depIdxs = nil
}
